### ISSUE TITLE
Nicer error when there is no toolchain at all

### ISSUE THREAD

**Issue by ianthehat** [katre/bazel#8]
When you try to use a toolchain that is not in the set available to the rule, you get a large stack trace and a confusing message as shown below.
It instead ought to tell you what toolchain type was being looked for in which rule.
```
java.lang.RuntimeException: Unrecoverable error while evaluating node 'CONFIGURED_TARGET://go/tools/builders:asm ad7b58a0da8c05bfb062b4f44d5e626c (116679763 1574316407)' (requested by nodes )
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:476)
	at com.google.devtools.build.lib.concurrent.AbstractQueueVisitor$WrappedRunnable.run(AbstractQueueVisitor.java:352)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: trying to assign null to toolchain
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:864)
	at com.google.devtools.build.lib.util.Preconditions.checkNotNull(Preconditions.java:368)
	at com.google.devtools.build.lib.syntax.LValue.assign(LValue.java:184)
	at com.google.devtools.build.lib.syntax.LValue.doAssign(LValue.java:125)
	at com.google.devtools.build.lib.syntax.LValue.assign(LValue.java:60)
	at com.google.devtools.build.lib.syntax.AssignmentStatement.doExec(AssignmentStatement.java:62)
	at com.google.devtools.build.lib.syntax.Statement.exec(Statement.java:31)
	at com.google.devtools.build.lib.syntax.UserDefinedFunction.call(UserDefinedFunction.java:83)
	at com.google.devtools.build.lib.syntax.BaseFunction.call(BaseFunction.java:429)
	at com.google.devtools.build.lib.rules.SkylarkRuleConfiguredTargetBuilder.buildRule(SkylarkRuleConfiguredTargetBuilder.java:84)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createRule(ConfiguredTargetFactory.java:336)
	at com.google.devtools.build.lib.analysis.ConfiguredTargetFactory.createConfiguredTarget(ConfiguredTargetFactory.java:225)
	at com.google.devtools.build.lib.skyframe.SkyframeBuildView.createConfiguredTarget(SkyframeBuildView.java:494)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.createConfiguredTarget(ConfiguredTargetFunction.java:1192)
	at com.google.devtools.build.lib.skyframe.ConfiguredTargetFunction.compute(ConfiguredTargetFunction.java:281)
	at com.google.devtools.build.skyframe.ParallelEvaluator$Evaluate.run(ParallelEvaluator.java:401)
	... 4 more
```

**Comment by katre** [comment]
Duplicates #1.
